version: '3.9'

services:
  web:
    user: root
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    command: gunicorn setup.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ./backend/:/app/
      - static_volume:/app/static/
      - media_volume:/app/media/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - db-dev
  frontend:
    user: root
    build:
      context: ./participation-form/
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./participation-form/:/app/
    ports:
      - 5173:5173
    depends_on:
      - web
  db-dev:
    image: postgres:15.1-alpine
    restart: always
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
  static_volume:
  media_volume:
